# Ansible playbook for provisioning

- hosts: localhost
  user: root
  vars_files:
    - "{{tmp_dir}}/vars.yml"
  tasks:
  - name: Clone the ai processing unit
    git:
      repo: https://github.com/Tekvot/aipu.git
      dest: /home/aipu/
      clone: yes
      update: yes
